# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 13:37
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnumber_ending', models.CharField(blank=True, max_length=4, verbose_name='Card number (last 4 digits)')),
                ('holder', models.CharField(blank=True, max_length=75, verbose_name='Card holder’s name')),
                ('address', models.CharField(blank=True, max_length=150, verbose_name='Billing address')),
                ('postcode', models.CharField(blank=True, max_length=15, verbose_name='Billing postcode')),
                ('expire_month', models.IntegerField(blank=True, choices=[('', 'Month'), (1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], null=True, verbose_name='Expiration month')),
                ('expire_year', models.IntegerField(blank=True, choices=[('', 'Year'), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)], null=True, verbose_name='Expiration year')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, choices=[('cc', 'Credit/Debit card'), ('pp', 'PayPal')], default='cc', max_length=2, verbose_name='Payment Method')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(choices=[('GBP', '£'), ('EUR', '€'), ('USD', '$')], default='GBP', max_length=3)),
                ('complete', models.BooleanField(default=False, verbose_name='Complete')),
                ('time_stamp', models.DateTimeField(default=datetime.datetime.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('plan', models.IntegerField(blank=True, choices=[(0, ''), (365, 'One year - £199'), (30, '30 days - £29')], default=0, null=True, verbose_name='Plan')),
                ('expires', models.DateTimeField(blank=True, null=True, verbose_name='active until')),
                ('recurring', models.BooleanField(default=False, help_text='Enable recurring billing', verbose_name='Recurring')),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='CardNumber',
            fields=[
                ('paycard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pay.PayCard')),
                ('encrypted', models.CharField(blank=True, editable=False, max_length=40, verbose_name='Encrypted PAN')),
            ],
        ),
        migrations.CreateModel(
            name='CardReceipt',
            fields=[
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pay.Payment')),
                ('details', models.CharField(blank=True, max_length=255)),
                ('authcode', models.CharField(blank=True, max_length=20)),
                ('reference', models.CharField(blank=True, max_length=20)),
                ('reason_code', models.CharField(blank=True, max_length=20)),
                ('avs_address', models.CharField(blank=True, choices=[('M', 'Matched'), ('N', 'Not Matched'), ('I', 'Problem with check'), ('U', 'Unable to check'), ('P', 'Partial Match')], max_length=1, verbose_name='AVS address check')),
                ('avs_postcode', models.CharField(blank=True, choices=[('M', 'Matched'), ('N', 'Not Matched'), ('I', 'Problem with check'), ('U', 'Unable to check'), ('P', 'Partial Match')], max_length=1, verbose_name='AVS postcode check')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paycard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cardreceipt',
            name='paycard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.PayCard'),
        ),
    ]
