# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardreceipt',
            name='paycard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pay.PayCard'),
        ),
    ]
