# Generated by Django 2.0.3 on 2018-03-25 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardreceipt',
            name='paycard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pay.PayCard'),
        ),
        migrations.AlterField(
            model_name='paycard',
            name='expire_year',
            field=models.IntegerField(blank=True, choices=[('', 'Year'), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027)], null=True, verbose_name='Expiration year'),
        ),
        migrations.AlterField(
            model_name='paycard',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (10, '10 days'), (20, '20 days'), (30, '30 days'), (180, '1/2 year - £60'), (365, 'one year - £90')], default=0, null=True, verbose_name='Plan'),
        ),
    ]
