# Generated by Django 2.0.4 on 2018-04-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0004_onupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='recurring',
            field=models.BooleanField(default=False, verbose_name='Auto-renew'),
        ),
    ]
